VERSION="2.2.1"

ACCOUNTS=["GBKAOR5BVSQRXP2RM2G3QKXKHRF46KTVN3KSTINP2EKAEHVNW7FIKIWI"]

[DOCUMENTATION]
ORG_NAME="KiwiRail"
ORG_URL="https://www.kiwi-stellar.org/"
ORG_DESCRIPTION="KiwiRail Holdings Limited is a New Zealand state-owned enterprise responsible for rail operations in New Zealand and operates inter-island ferries."
ORG_LOGO="https://www.kiwi-stellar.org/kiwi.png"


[[CURRENCIES]]
code="KIWI"
status="live"
display_decimals=4
issuer="GBKAOR5BVSQRXP2RM2G3QKXKHRF46KTVN3KSTINP2EKAEHVNW7FIKIWI"
anchor_asset_type="crypto"
name="KiwiRail"
desc="KiwiRail Holdings Limited is a New Zealand state-owned enterprise responsible for rail operations in New Zealand and operates inter-island ferries."
image="https://www.kiwi-stellar.org/kiwi.png"
